### ISSUE TITLE
Syncing of collections from git repos fails to clone any submodules

### ISSUE THREAD

**Issue by dkliban** [pulp/pulp_ansible#1065]
`test_sync_collection_from_git` is failing because the `pulp_installer` collection now has a symlink to a file in the `forklift` submodule. The `git` remote needs to make sure that it also clones all submodules in a git repository.

**Comment by mdellweg** [comment]
like `git clone --recurse-submodules` ?

**Comment by dkliban** [comment]
@mdellweg exactly that. I was able to add that to the git clone command, but now it seems like galaxy-importer has a bug related to this also.

**Comment by jctanner** [comment]
This happens because the project's galaxy.yml has been configured to ignore the forklift directory at collection build time https://github.com/pulp/pulp_installer/blob/main/galaxy.yml#L88
