### ISSUE TITLE
Requirments conflict while installing pulp-ansible

### ISSUE THREAD

**Issue by TheFieryLynx** [pulp/pulp_ansible#1366]
**Version**
latest pulpcore(3.22.2) and pulp-ansible(0.16.0)

**Describe the bug**
``fatal: [localhost]: FAILED! => {
    "changed": false,
    "cmd": [
        "/usr/local/lib/pulp/bin/pip-compile"
    ],
    "delta": "0:00:18.356153",
    "end": "2023-02-21 16:43:59.472344",
    "failed_when_result": true,
    "invocation": {
        "module_args": {
            "_raw_params": "/usr/local/lib/pulp/bin/pip-compile    ",
            "_uses_shell": false,
            "argv": null,
            "chdir": "/usr/local/lib/pulp",
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true
        }
    },
    "msg": "non-zero return code",
    "rc": 2,
    "start": "2023-02-21 16:43:41.116191",
    "stderr": "WARNING: the legacy dependency resolver is deprecated and will be removed in future versions of pip-tools. The default resolver will be changed to 'backtracking' in pip-tools 7.0.0. Specify --resolver=backtracking to silence this warning.\nUsing legacy resolver. Consider using backtracking resolver with `--resolver=backtracking`.\nCould not find a version that matches packaging<22,>=21.0,>=21.3,>=22.0 (from pulp-ansible==0.16.0->-r requirements.in (line 2))\nTried: 14.0, 14.0, 14.1, 14.1, 14.2, 14.2, 14.3, 14.3, 14.4, 14.4, 14.5, 14.5, 15.0, 15.0, 15.1, 15.1, 15.2, 15.2, 15.3, 15.3, 16.0, 16.0, 16.1, 16.1, 16.2, 16.2, 16.3, 16.3, 16.4, 16.4, 16.5, 16.5, 16.6, 16.6, 16.7, 16.7, 16.8, 16.8, 17.0, 17.0, 17.1, 17.1, 18.0, 18.0, 19.0, 19.0, 19.1, 19.1, 19.2, 19.2, 20.0, 20.0, 20.1, 20.1, 20.2, 20.2, 20.3, 20.3, 20.4, 20.4, 20.5, 20.5, 20.6, 20.6, 20.7, 20.7, 20.8, 20.8, 20.9, 20.9, 21.0, 21.0, 21.1, 21.1, 21.2, 21.2, 21.3, 21.3, 22.0, 22.0, 23.0, 23.0\nThere are incompatible versions in the resolved dependencies:\n  packaging>=22.0 (from black==23.1.0->ansible-lint==6.13.1->galaxy-importer==0.4.6->pulp-ansible==0.16.0->-r requirements.in (line 2))\n  packaging<22,>=21.3 (from pulp-ansible==0.16.0->-r requirements.in (line 2))\n  packaging>=21.3 (from ansible-lint==6.13.1->galaxy-importer==0.4.6->pulp-ansible==0.16.0->-r requirements.in (line 2))\n  packaging (from bleach==3.3.1->galaxy-importer==0.4.6->pulp-ansible==0.16.0->-r requirements.in (line 2))\n  packaging>=21.0 (from django-lifecycle==1.0.0->pulpcore==3.22.2->-r requirements.in (line 1))\n  packaging (from ansible-core==2.14.2->galaxy-importer==0.4.6->pulp-ansible==0.16.0->-r requirements.in (line 2))\n  packaging (from bindep==2.11.0->ansible-builder==1.2.0->galaxy-importer==0.4.6->pulp-ansible==0.16.0->-r requirements.in (line 2))",
    "stderr_lines": [
        "WARNING: the legacy dependency resolver is deprecated and will be removed in future versions of pip-tools. The default resolver will be changed to 'backtracking' in pip-tools 7.0.0. Specify --resolver=backtracking to silence this warning.",
        "Using legacy resolver. Consider using backtracking resolver with `--resolver=backtracking`.",
        "Could not find a version that matches packaging<22,>=21.0,>=21.3,>=22.0 (from pulp-ansible==0.16.0->-r requirements.in (line 2))",
        "Tried: 14.0, 14.0, 14.1, 14.1, 14.2, 14.2, 14.3, 14.3, 14.4, 14.4, 14.5, 14.5, 15.0, 15.0, 15.1, 15.1, 15.2, 15.2, 15.3, 15.3, 16.0, 16.0, 16.1, 16.1, 16.2, 16.2, 16.3, 16.3, 16.4, 16.4, 16.5, 16.5, 16.6, 16.6, 16.7, 16.7, 16.8, 16.8, 17.0, 17.0, 17.1, 17.1, 18.0, 18.0, 19.0, 19.0, 19.1, 19.1, 19.2, 19.2, 20.0, 20.0, 20.1, 20.1, 20.2, 20.2, 20.3, 20.3, 20.4, 20.4, 20.5, 20.5, 20.6, 20.6, 20.7, 20.7, 20.8, 20.8, 20.9, 20.9, 21.0, 21.0, 21.1, 21.1, 21.2, 21.2, 21.3, 21.3, 22.0, 22.0, 23.0, 23.0",
        "There are incompatible versions in the resolved dependencies:",
        "  packaging>=22.0 (from black==23.1.0->ansible-lint==6.13.1->galaxy-importer==0.4.6->pulp-ansible==0.16.0->-r requirements.in (line 2))",
        "  packaging<22,>=21.3 (from pulp-ansible==0.16.0->-r requirements.in (line 2))",
        "  packaging>=21.3 (from ansible-lint==6.13.1->galaxy-importer==0.4.6->pulp-ansible==0.16.0->-r requirements.in (line 2))",
        "  packaging (from bleach==3.3.1->galaxy-importer==0.4.6->pulp-ansible==0.16.0->-r requirements.in (line 2))",
        "  packaging>=21.0 (from django-lifecycle==1.0.0->pulpcore==3.22.2->-r requirements.in (line 1))",
        "  packaging (from ansible-core==2.14.2->galaxy-importer==0.4.6->pulp-ansible==0.16.0->-r requirements.in (line 2))",
        "  packaging (from bindep==2.11.0->ansible-builder==1.2.0->galaxy-importer==0.4.6->pulp-ansible==0.16.0->-r requirements.in (line 2))"
    ],
    "stdout": "",
    "stdout_lines": []
}``

**install.yml**
\- hosts: localhost
  force_handlers: True
  collections:
    \- pulp.pulp_installer
  vars:
    pulp_webserver_disable_https: True
    pulp_settings:
      force_ignore_missing_package_indices: True
      secret_key: "some_key"
      content_origin: "{{ pulp_webserver_disable_https | default(false) | ternary('http', 'https') }}://ip"
      allowed_content_checksums:
        \- sha1
        \- md5
        \- sha224
        \- sha256
        \- sha384
        \- sha512
    pulp_default_admin_password: passwd
    pulp_install_plugins:
      \# galaxy-ng:
      \# pulp-2to3-migration:
      pulp-ansible:
      \# pulp-certguard:
      \# pulp-container:
      \# pulp-cookbook:
      \# pulp-deb:
      \# pulp-file:
      \# pulp-gem:
      \# pulp-maven:
      \# pulp-npm:
      \# pulp-python:
      \# pulp-rpm:
  roles:
    \- pulp_all_services
  environment:
    DJANGO_SETTINGS_MODULE: pulpcore.app.settings

**Question**
pip-tools and other packages requires too high version for packaging. It seems that the version for the packaging is fixed in requirments.txt. Are there any ways to correctly register versions for plugins or packages?
Thank you in advance

**Comment by TheFieryLynx** [comment]
UPD: need to fix packaging==21.3 and black==22.12.0 for pulp-ansible!

**Comment by mdellweg** [comment]
I'm wandering where the dependency on black comes from. The one on packages is dropped from the main branch. Not sure, if it is needed in 0.16.

**Comment by TheFieryLynx** [comment]
![image](https://user-images.githubusercontent.com/61374701/220633464-a0e4e6e9-77ac-4678-a75a-6f70fe07cbcd.png)

Decided to rerun pulp_installer on completely clean system. The same error in dependencies. The only solution I found is to remove all packages from venv and install black version 22 instead of version 23 -> it has a dependency on packaging==21.3, which fits all dependencies. And after this manipulation rerun pulp_installer again and everything is installed successfully.

My install.yml for pulp_installer:
![image](https://user-images.githubusercontent.com/61374701/220634892-aa69fb12-7ec0-49a9-a1a0-ba00b29a19bf.png)

**Comment by mdellweg** [comment]
Again, pip is not the best in dependency resolution out there.
But i think, the solution is to try to drop the requirement on packaging in pulp_ansible 0.16.
Also you could ask ansible-lint to soften the black requirement (either a larger range, or an optional dep).
