### ISSUE TITLE
Sync should not fail if namespace's avatar fails to download

### ISSUE THREAD

**Issue by gerrod3** [pulp/pulp_ansible#1543]
Allow the sync pipeline to skip bad downloads of namespace avatars to make sync more resilient. 

Related:
https://github.com/pulp/pulp_ansible/issues/1415

**Comment by newswangerd** [comment]
Jira: 
- https://issues.redhat.com/browse/AAH-2619
- https://issues.redhat.com/browse/AAP-14090
