### ISSUE TITLE
Add `count` attribute to `TagSerializer`

### ISSUE THREAD

**Issue by jerabekjiri** [pulp/pulp_ansible#1612]
**Is your feature request related to a problem? Please describe.**

Old galaxy (https://old-galaxy.ansible.com/search) has a list of popular tags. Since we're reusing `TagSerializer` it would be useful to add this to `TagSerializer` in pulp_ansible.
![Screenshot from 2023-10-10 13-29-31](https://github.com/pulp/pulp_ansible/assets/19647757/4c690fa5-cf51-4d91-b15b-60f07346cb08)

**Describe the solution you'd like**
Update `TagSerializer` with
```
    count = serializers.SerializerMethodField()

    def get_count(self, obj):
        return obj.ansible_collectionversion.count()

    class Meta:
        model = Tag
        fields = ["name", "count"] 
```

**Describe alternatives you've considered**
If this doesn't work out, we can add it to galaxy_ng codebase.

**Comment by mdellweg** [comment]
sounds feasible...
