### ISSUE TITLE
pulp_ansible 0.23.1 not installable via PyPi

### ISSUE THREAD

**Issue by fullsushidev** [pulp/pulp_ansible#2052]
**Version**
pulp_ansible 0.23.1

**Describe the bug**
The pulp_ansible 0.23.1 failed to publish to PyPi:
https://github.com/pulp/pulp_ansible/actions/runs/11979951934/job/33403203819

**Comment by mdellweg** [comment]
The release is now uploaded by hand.
The corresponding CI fix is supposed to come with this PR: https://github.com/pulp/plugin_template/pull/930
