### ISSUE TITLE
syncing 100+ collections causes OOM on 1Gi resource limited pods.

### ISSUE THREAD

**Issue by gamuniz** [pulp/pulp_ansible#765]

**Comment by fao89** [comment]
Ref: 
- https://github.com/pulp/pulp-operator/issues/303
- https://issues.redhat.com/browse/AAP-1376

**Comment by mdellweg** [comment]
The original reproducer for this seems to have gone.
If you feel there is still some necessary performance / resource issue to be solved, please reopen.
