### ISSUE TITLE
Deprecation content migration error.

### ISSUE THREAD

**Issue by newswangerd** [pulp/pulp_ansible#791]
When upgrading to pulp ansible 0.10, I get this error:

```
django.db.utils.IntegrityError: could not create unique index "ansible_ansiblecollectio_namespace_name_e1aa1c6d_uniq" DETAIL: Key (namespace, name)=(splunk, enterprise_security) is duplicated. 
```

Steps to reproduce:
- upload two versions of a collection to pulp ansible
- move one of the versions to a new repository
- attempt to perform the upgrade

After performing the failed upgrade, it looks like there is a duplicate collection deprecated content for each repository that the deprecated content was in:

```
galaxy_ng=# select * from ansible_ansiblecollectiondeprecated;
            content_ptr_id            |  namespace  |      name       |            collection_id             |            repository_id             |           version_added_id
--------------------------------------+-------------+-----------------+--------------------------------------+--------------------------------------+--------------------------------------
 ee99298a-86b3-48a1-8aba-6e105b5075eb | newswangerd | main_collection | 41ad8982-f094-4e28-8520-d2e0a119f2ab | fe424277-a0c2-4df0-b4e5-3324b2e2de90 | fe4a53d5-afa7-40c0-ba52-c89dace5a147
 5fca8a31-5562-46cb-bac2-d57cfbcc875c | newswangerd | main_collection | 41ad8982-f094-4e28-8520-d2e0a119f2ab | eb3573b9-1281-4dd7-9ea8-3a40b356892c | bfcee45c-1327-4b18-baf6-f02d483c5be7
 ```

My theory is that these duplicates are getting created here when the data is migrated from the old deprecation table to the new one: https://github.com/pulp/pulp_ansible/blob/main/pulp_ansible/app/migrations/0035_deprecation_content.py#L16

**Comment by bmbouter** [comment]
What version of pulp_ansible should we use to upgrade from? Also what versions of pulpcore should be used pre and post upgrade?

**Comment by newswangerd** [comment]
@bmbouter Hub 4.3 to 4.4: https://github.com/ansible/galaxy_ng/wiki/Galaxy-NG-Pulp-Requirments

So pulp_ansible 0.7 -> 0.10 and pulpcore 3.11 -> 3.15

**Comment by mdellweg** [comment]
Don't you need to deprecate something in the steps to reproduce?
