### ISSUE TITLE
0.7 sync not excluding v3/excludes

### ISSUE THREAD

**Issue by awcrosby** [pulp/pulp_ansible#959]
**Version**
galaxy_ng dev environment running:
galaxy_ng==4.3.5
pulpcore==3.11.2
pulp-ansible==0.7.4

**Describe the bug**
- Performing a sync with galaxy_ng 4.5.0 with pulp-ansible==0.13.0 against console.stage.redhat.com yields the expected result: collections in the v3/excludes endpoint are not sync’d.
- Doing the same with galaxy_ng 4.3.5 with pulp-ansible==0.7.4 does not exclude the collections at v3/excludes, this is expected since there is a backport of this: https://github.com/pulp/pulp_ansible/commit/41f79c6c128f0cc6ab70dc56a4d348493c0227dc

**To Reproduce**
Sync against https://console.stage.redhat.com/api/automation-hub/content/6089719-synclist/ 

**Expected behavior**
Collections sync'd should not include https://console.stage.redhat.com/api/automation-hub/content/6089719-synclist/v3/excludes/

**Additional context**
This is mentioned and tracked in https://issues.redhat.com/browse/AAH-1583

**Comment by gerrod3** [comment]
I figured out the issue. An early version of the exclude sync was backported. This version required setting the excluded collections on the sync task, but since excludes was put into an endpoint it was changed later and never backported (again).
